cd_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: CDUserBundle:Default:index }

cd_user_index:
    path:     /user/index
    defaults: { _controller: CDUserBundle:User:index }
    
cd_user_add:
    path:     /user/add
    defaults: { _controller: CDUserBundle:User:add }

cd_user_create:
    path:     /user/create
    defaults: { _controller: CDUserBundle:User:create }
    methods: POST

cd_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: CDUserBundle:User:edit }
    
cd_user_update:
    path:     /user/update/{id}
    defaults: { _controller: CDUserBundle:User:update }
    methods: [POST, PUT]
    
cd_user_view:
    path:     /user/view/{id}
    defaults: { _controller: CDUserBundle:User:view }
    
cd_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: CDUserBundle:User:delete }
    methods: [POST, DELETE]
    
cd_user_redirect_add:
    path:     /user/create
    defaults: 
        _controller: CDUserBundle:User:add 
        path: /user/add
        permanent: true

cd_user_redirect_edit:
    path:     /user/update/{id}
    defaults: 
        _controller: CDUserBundle:User:edit 
        path: /user/edit/{id}
        permanent: true
    